name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  cmdstanVersion: "2.28.1"

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}
            /home/runner/.cmdstan
          key: ${{ env.pythonLocation }}-${{ hashFiles('test_requirements.txt') }}
      - name: "Install dependencies"
        run: |
          pip install -r test_requirements.txt
          python -m cmdstanpy.install_cmdstan --version ${{ env.cmdstanVersion }}
      - name: "Build the project"
        run: "make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
